#!/bin/bash

function ff() {
    find / -name "$1" 2>/dev/null
}

function cmg() {
    cmake -E make_directory build && cmake -E chdir build cmake -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. 
}

function bb() {
    cmake --build build && cmake -E chdir build ctest --output-on-failure
}

function gitstat() {
    git shortlog -s -n --all --no-merges
}

alias gg='git status'
alias ss='source ~/.zshrc'
alias generateycm='ln -s ~/dotfiles/ycm_config/ycm_extra_conf.py .ycm_extra_conf.py'
# search and replace in file -> find -name \*.cpp | xargs sed -i -e 's/MATCH/REPLACEMENT/g'
