# Load stuff
autoload -U promptinit && promptinit
autoload -U colors && colors

# Check if Git repo
function prompt_git {
  if git rev-parse --git-dir > /dev/null 2>&1; then
     echo '»' 
  else 
     echo '›' 
  fi
}
# Load the prompt
prompt="%{$fg[green]%}$(prompt_git) %{$fg[blue]%}%~%{$reset_color%} "

# History settings
HISTFILE=~/.zsh_history         # where to store zsh config
HISTSIZE=1024                   # big history
SAVEHIST=1024                   # big history
setopt append_history           # append
setopt hist_ignore_all_dups     # no duplicate
unsetopt hist_ignore_space      # ignore space prefixed commands
setopt hist_reduce_blanks       # trim blanks
setopt hist_verify              # show before executing history commands
setopt inc_append_history       # add commands as they are typed, dont wait until shell exit 
setopt share_history            # share hist between sessions
setopt bang_hist                # !keyword

bindkey -v      # vi mode

if [ -d "/opt/cmake-3.12.2-Linux-x86_64/bin" ]; then
    export PATH=/opt/cmake-3.12.2-Linux-x86_64/bin:${PATH}
fi
if [ -f "${HOME}/.cargo/env" ]; then
    source ${HOME}/.cargo/env
fi
source ~/.aliases
if [ -e ~/local-aliases ]; then
    source ~/local-aliases
fi
