# Load stuff
autoload -U promptinit && promptinit
autoload -U colors && colors

git_prompt() {
  ref=$(git symbolic-ref HEAD 2>/dev/null | cut -d'/' -f3-)
  echo $ref
}

# Load the prompt
prompt="%{$fg[green]%}› %{$fg[blue]%}%~%{$reset_color%} "

# History settings
HISTFILE=~/.zsh_history         # where to store zsh config
HISTSIZE=1024                   # big history
SAVEHIST=1024                   # big history
setopt append_history           # append
setopt hist_ignore_all_dups     # no duplicate
unsetopt hist_ignore_space      # ignore space prefixed commands
setopt hist_reduce_blanks       # trim blanks
setopt hist_verify              # show before executing history commands
setopt inc_append_history       # add commands as they are typed, dont wait until shell exit 
setopt share_history            # share hist between sessions
setopt bang_hist                # !keyword

bindkey -v      # vi mode

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

function zle-line-init zle-keymap-select {
  VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
  RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}$(git_prompt) $EPS1"
  zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
export KEYTIMEOUT=1

if [ -d "/opt/cmake-3.12.2-Linux-x86_64/bin" ]; then
    export PATH=/opt/cmake-3.12.2-Linux-x86_64/bin:${PATH}
fi
if [ -f "${HOME}/.cargo/env" ]; then
    source ${HOME}/.cargo/env
fi
source ~/.aliases
